# Stand Structure

Stand structure is defined as. 

## Basal area ($BA$)

Basal area is the common term used to describe the average amount of an area (usually an acre) occupied by tree stems. It is defined as the total cross-sectional area of all stems in a stand measured at breast height, and expressed as per unit of land area (typically square feet per acre or square meters per hectare). Basal area may also refer to the cross-sectional area of an individual tree.

Basal area per individual tree:  $BA = \Pi \times (DBH/2)^2$  


Also see:  
[Diameter-at-breash height ($DBH$)](## Diameter-at-breast height ($DBH$))  


## Diameter-at-breast height ($DBH$)

Diameter at breast height, or DBH, is a standard method of expressing the diameter of the trunk or bole of a standing tree. DBH is one of the most common dendrometric measurements and typically taken at a height of approximately 1.3 m (4.3 ft) above ground. Units are most typically in cm or in.  

Measurement methods:  
- DBH tape  
- Calipers  
- Electronic calipers  


## DBH class diversity ($H'$)

DBH class diversity, or $H'$, is a structural diversity index derived from the proportional abundance of trees in different diameter or DBH classes. The Shannon-Wiener Index ($H$), a widely used biodiversity or diversity index is used as the basis for calculating $H'$.

$$H' = -\sum_{i=1}^{n} pi\ln(pi)$$  
$H'$ reaches its maximum value at $\ln(n)$.    

References:  
[Morgenroth et al. 2020](https://doi.org/10.3390/f11020135)


## Gini Coefficent

Gini coefficient, sometimes called the Gini index or Gini ratio, is a measure of statistical dispersion and descriptor of stand inequality. It is continuous and directly related to size hierarchy and linked to asymmetric competition between trees. Several studies have indicated it performs better in discriminating stands of different diameter distributions. Designed originally for studying economic inequality, it has been broadly applied in forestry and ecology.  

$$Gini = 2\frac{\sum_{i = 1}^{n}ig_i}{nG} - \frac{n + 1}{n}$$  

Where $g_i$ is the basal area of tree $i$, and $G$ is the total basal area of $n$ the number of trees.  

References:  
[Bourdier et al. (2016)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4801349/pdf/pone.0151852.pdf)


Also see:  
[Gini Coefficient on Wikipedia](https://en.wikipedia.org/wiki/Gini_coefficient)  




