# Height
Now let's talk details.

## Canopy relief ratio ($CRR$)  

A measure of the relative shape of the canopy from lidar or altimetry. Also known as the elevation relief ratio ($ERR$).

$$CRR = \frac{h_{mean} - h_{min}}{h_{max} - h_{max}}$$

See also:  
Parker and Russ, 2004

## Mean outer canopy height {$MOCH$}

$MOCH$ is the mean or average height of the outer canopy ($Z_m$) of a forest based on 
some resolution, $X$ or $X,Y$. For example, for aerial lidar scanning or ALS, $MOCH$
can be calculated from a canopy height model (CHM) as the mean value of each $Z$ over a
defined $X,Y$ coordinate space or as the mean of all values in that CHM. For terrestrial lidar (TLS), 
$MOCH$ is often defined as the average of the highest lidar return (also defined as $Z_max$) 
for each $X$ or $X,Y$ coordinate space with a standard resolution of 1 m. 

See also:  

[Maximum canopy height ($H_{max}$)](## Maximum canopy height ($H_{max}$))  


## Mean height ($H$)

Mean height, also mean canopy height or $H$ is a lidar derived metric measuring
the mean return height of all lidar pulses in some $X,Y$ defined coordinate space,
and defined spatial resolution. For TLS and UAV based sensors this resolution is often 1 m, 
while for ALS is typically 10 to 30 m. 

See also:  

[$p50$](### $p50$)  


## Maximum canopy height ($H_{max}$)

## Percentile heights

### p10
### p50